version: "3.7"

services:
  gits-frontend:
    build: .
    ports:
      - "3000:3000"

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
