version: "3.7"

services:
  gits-frontend:
    build:
      context: ./../gits-frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: "http://localhost:8080/graphql"
        NEXT_PUBLIC_OAUTH_REDIRECT_URL: "http://localhost:3005"
        NEXT_PUBLIC_OAUTH_CLIENT_ID: "gits-frontend"
        NEXT_PUBLIC_OAUTH_AUTHORITY: "http://localhost:9009/realms/GITS"
    ports:
      - "3005:3000"

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    ports:
      - "9009:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev --import-realm
    volumes:
      - type: bind
        source: ./../gits-frontend/keycloak-realm
        target: /opt/keycloak/data/import
