name: Testing CI

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.3.1

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 19.9.0
          cache: pnpm

      - name: Install packages
        run: pnpm install --frozen-lockfile

      - name: Run relay compiler
        run: mkdir ./__generated__ && pnpm run relay

      - name: Build project
        run: pnpm run build --no-lint

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.3.1

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 19.9.0
          cache: pnpm

      - name: Install packages
        run: pnpm install --frozen-lockfile

      - name: Run eslint
        run: pnpm run lint

  style-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.3.1

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 19.9.0
          cache: pnpm

      - name: Install packages
        run: pnpm install --frozen-lockfile

      - name: Run prettier
        run: pnpm run check-format
